#!/usr/bin/env ansible-playbook

---
- hosts: all
  become: yes
  # gather_facts: true
  vars_files:
    - defaults/main.yml

  tasks:
    - name: "Delegate installation process"
      include: "tasks/use-{{ ansible_os_family }}.yml"

    - name: "VMware automation specific configurations"
      import_tasks: "tasks/vmware.yml"
      include: lookup('env','PLATFORM') == "vmware"

    - name: "Configure environment"
      include: "tasks/main.yml"