#!/usr/bin/env ansible-playbook

---
- hosts: all
  become: yes
  # gather_facts: true
  vars_files:
    - defaults/main.yml

  tasks:
    - name: "Delegate installation process"
      include_tasks: "tasks/use-{{ ansible_os_family }}.yml"

    - name: "VMware automation specific configurations"
      include_tasks: "tasks/vmware.yml"
      when: lookup('env','PLATFORM') == "vmware"

    - name: "Configure environment"
      include_tasks: "tasks/main.yml"