#!/usr/bin/env ansible-playbook

---

- name: delegate installation process
  include: "use-{{ ansible_pkg_mgr }}.yml"

- name: copy s2i scripts
  copy:
    src: files/s2i/bin
    dest: /root/xmr-cronjob.sh
    directory_mode: yes