#!/usr/bin/env ansible-playbook

---

- name: delegate installation process
  include: "use-{{ ansible_pkg_mgr }}.yml"

- name: Add default user
  user:
    name: default
    comment: "Default Application User"
    uid: 1001
    group: root
    shell: /sbin/nologin
    home: "{{ ansible_env.HOME }}"

- name: Create home directory for default user
  file:
    path: "{{ ansible_env.HOME }}"
    owner: default
    group: root
    state: directory
    recurse: yes
    mode: 0775

- name: Configure ACL permission for default user
  acl:
    path: "{{ ansible_env.HOME }}"
    entity: default
    etype: user
    permissions: rwx
    recursive: yes
    default: yes
    state: present

- name: print environment variable
  debug:
    msg: "{{ ansible_env.HOME }}"