#!/usr/bin/env ansible-playbook

---

# - debug:
#     msg: "var = {{ lookup('env','PLATFORM') }}"

# - debug:
#     msg: "this is vmware"
#   when: lookup('env','PLATFORM') == "vmware"

# - debug:
#     msg: "this is openstack"
#   when: lookup('env','PLATFORM') == "openstack"

- name: "Add default user"
  user:
    name: default
    comment: "Default Application User"
    uid: 1001
    group: root
    shell: /sbin/nologin
    home: "{{ ansible_env.HOME }}"

- name: Create home directory for default user
  file:
    path: "{{ ansible_env.HOME }}"
    owner: default
    group: root
    state: directory
    recurse: yes
    mode: 0775

- name: Create /etc/password file permission
  file:
    path: "/etc/passwd"
    mode: 0775

- name: Configure ACL permission for default user
  acl:
    path: "{{ ansible_env.HOME }}"
    entity: default
    etype: user
    permissions: rwx
    recursive: yes
    default: yes
    state: present
