#!/usr/bin/env ansible-playbook

---

- name: "(VMware Automation) Install necessary python modules for Ansible"
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - "jmespath"
    - "pysphere"
    - "pyVmomi"
    - "PyYAML"